apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 342173645329.dkr.ecr.us-east-1.amazonaws.com/myecr:latest
          ports:
            - containerPort: 8080